#
# Settings for date extraction runs
# Only the final .sno at the end date is saved (no intermediate backups)
#
[OUTPUT]
PROF_WRITE		=	TRUE
TS_WRITE		=	TRUE
BACKUP_DAYS_BETWEEN	=	0
FIRST_BACKUP		=	0
OUT_HAZ			=	FALSE
